### ISSUE TITLE
Roof Mapping Effects Aren't Working

### ISSUE THREAD

**Issue by AndrewL97** [Mojave-Sun/mojave-sun#100]
Not setting roofType var correctly.

**Comment by uomo91** [comment]
This was apparently a result of people using the base type instead of the wood child type.

**Comment by uomo91** [comment]
I'm declaring this fixed for now.
https://github.com/Mojave-Sun/mojave-sun/pull/110

In the future more static roof helper types, or perhaps dynamically generated ones, would be something we'll potentially need.
