### ISSUE TITLE
Remove/nerf gamey SS13 elements (chem grenades, botany, etc)

### ISSUE THREAD

**Issue by AndrewL97** [Mojave-Sun/mojave-sun#17]

**Comment by Hekzder** [comment]
A fair bit of this is dependent upon the chemistry system of what exactly we remove and don't. But a lot of the base SS13 silly stuff is going to be gone, IE base SS13 chem nades, explosive lemons ambrosia gaia, etc.

**Comment by AndrewL97** [comment]
@Koshenko @Hekzder we can wangle this out post go-live, we will have a better grasp on how gamey stuff is when players start using it - re add the tag if you disagree
