### ISSUE TITLE
Currently our road decals aren't loading in it would seem.

### ISSUE THREAD

**Issue by ProfessorPopoff** [Mojave-Sun/mojave-sun#229]
![image](https://user-images.githubusercontent.com/51188571/104794495-fc436f00-5775-11eb-877d-405f05ea25a0.png)
It seems like this is more than just me. I'll leave this here.

**Comment by scarwolff** [comment]
could be a layering or timing issue, something to consider on the new rebase for these now bald ass roads

**Comment by ProfessorPopoff** [comment]
I suppose while we're on a kicker about actually typing in these issues. This problem has to do with inheritance in the update_icon procs in both the sidewalk and the road.
