### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by Scrub-trash** [Mojave-Sun/mojave-sun#338]
## Reproduction:
Attempt to compile in DM, get issues with the files: (code/game/objects/items/toy mechs.dm) and (code/modules/vehicles/mecha/equipment/weapons/weapons.dm) - chassis?.to_chat and target?.to_chat prevent compiling.

**Comment by infraredbaron** [comment]
Sorry pal, you need some files from gitlab, which are accessible only via our discord.
¯\_(ツ)_/¯

**Comment by Koshenko** [comment]
It's likely an issue with tgstation upstream.  We'll likely have a fix soon once we update a few things.
