### ISSUE TITLE
New lighting system bugs

### ISSUE THREAD

**Issue by Koshenko** [Mojave-Sun/mojave-sun#38]
## Reproduction:

![largeshadowabove](https://user-images.githubusercontent.com/53068134/86435613-399e4e80-bcb5-11ea-9f7c-3d5f013ffb27.png)
![largershadow](https://user-images.githubusercontent.com/53068134/86435622-402cc600-bcb5-11ea-982c-9bdd32e6d2af.png)
Shadows seem to have issues with newly created turfs whether above or below.  Ceilings tend to create black squares, while walls tend to just turn black and not affect the lighting around them (even if they partially enclose a space)
![beforeexplosion](https://user-images.githubusercontent.com/53068134/86435634-4753d400-bcb5-11ea-9292-89354e818444.png)
![girderglitch](https://user-images.githubusercontent.com/53068134/86435647-4de24b80-bcb5-11ea-81ef-585d713b72a6.png)
![aftersyndieclusterbomb](https://user-images.githubusercontent.com/53068134/86435667-5470c300-bcb5-11ea-8a56-18b660b03c59.png)
Explosions (if large enough) can cause quite a few issues.  It might be a lack of updating on explosive acts.  I couldn't get a good video of it, but the light objects on the turfs seem to slowly update square by square trying to reconfigure the lighting matrix.

**Comment by AndrewL97** [comment]
Thanks for finding, ill have a looky loo

**Comment by Koshenko** [comment]
![floating turf](https://user-images.githubusercontent.com/53068134/86705248-8a21ee80-bfca-11ea-8408-27229264cdfe.png)
![big shadow](https://user-images.githubusercontent.com/53068134/86705262-8d1cdf00-bfca-11ea-84c8-f2f00f9bf6b4.png)
It seems as though the issue with shadows and turfs setup by debug/game panel after roundstart still have some issue with producing proper shadows.

![floating roof](https://user-images.githubusercontent.com/53068134/86705358-a58cf980-bfca-11ea-98a1-c0b7fce61a28.png)
![floating shadow](https://user-images.githubusercontent.com/53068134/86705373-a9b91700-bfca-11ea-8705-7a90bdf5f181.png)
This floating roof (a letover of a previous mapping PR) seems to have generated its shadows just fine, so it seems like admin placed turfs may have issues due to bypassing most of the normal procs used for construction of turfs.  This shouldn't be too much of an issue as long as new code which builds turfs properly triggers a sunlight shadow update.

Player built turf roofs seem to be absolutely fine.
![player made roof](https://user-images.githubusercontent.com/53068134/86706066-5d220b80-bfcb-11ea-88c0-3227a88f2d3e.png)
![player made shadow](https://user-images.githubusercontent.com/53068134/86706086-61e6bf80-bfcb-11ea-9ecf-04bf0f6c6de4.png)

**Comment by Koshenko** [comment]
Issues seem to be resolved for now.  Will open a new one if we have anymore lighting issues.
